apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore
  # This is an extra long description
  description: The Petstore is an example API used to show features of the OpenAPI spec.
  annotations:
    gitlab.com/project-slug: 'project-slug'
    gitlab.wirecard-cloud.com/project-slug: 'project-slug'
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
spec:
  type: service
