---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.application_name | dump}}
  namespace: argocd
spec:
  destination:
    namespace: ${{values.namespace | dump}}
    server: https://kubernetes.default.svc
  project: ${{values.project_name | dump}}
  source:
    path: deploy/
    repoURL: ${{values.repoUrl | dump}}
    # repoURL: https://github.com/Tomelin/argocd-backstage.git
    targetRevision: HEAD
---
repoUrl: ${{ (parameters.repoUrl }}
parseRepoUrl: ${{ (parameters.repoUrl | parseRepoUrl) }}
owner: ${{ (parameters.repoUrl | parseRepoUrl)["owner"] }}
repo: ${{ (parameters.repoUrl | parseRepoUrl)["repo"] }}
