---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ${{values.project_name | dump}}
  namespace: argocd
spec:
  {% if values.description %}
  description: ${{values.description | dump}}
  {% endif %}
  destinations:
  - namespace: ${{values.namespace | dump}}
  for:
    {% for item in values.project_name %}
      Value: {{ item }}
    {% endfor %}  
---
 {% for item in values.list %}
    Value: {{ item }}
  {% endfor %}  
  
   {% for idx in values %}
    Value: {{ idx }}
    index: {{ idx.index }}
  {% endfor %}  

  {% for row in values %}
  value => {{ row }}
  value => {{ row.index }}

    {# new row #}
    <tr>
    {% set rowloop = loop %}
    {% for cell in row %}
      <td>
          row (rowloop.index):{{ rowloop.index }}
          column (loop.index): {{ loop.index }}
          cell: {{ cell }}
      </td>
    {% endfor %}
    </tr>
  {% endfor %}
