---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ${{values.project_name | dump}}
  namespace: argocd
spec:
  {% if values.description %}
  description: ${{values.description | dump}}
  {% else %}
  description: "ArgoCD project ${{ values.project_name }}"
  {% endif %}
  destinations:
  - namespace: ${{values.project_name | dump}}
    server: "*"  # cluster 
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy
  orphanedResources:
    warn: false
  syncWindows:
  - kind: allow
    schedule: '10 1 * * *'
    duration: 1h
    applications:
      - '*-prod'
    manualSync: true
  - kind: deny
    schedule: '0 22 * * *'
    duration: 1h
    namespaces:
      - default
  - kind: allow
    schedule: '0 23 * * *'
    duration: 1h
    clusters:
      - in-cluster
      - cluster1
