---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
 {%- if values.argocd %}
- https://github.com/Tomelin/argocd-appProject/common
 {%- endif %}

patches:
{%- if values.argocd %}
# STARTS ArgoCD
- target:
    kind: AppProject
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: ${{values.project_name | dump}}
    - op: replace
      path: /spec/destinations/0/namespace
      value: ${{values.project_name | dump}}
- target:
    kind: Application
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: ${{values.application_name | trim | dump}}
    - op: replace
      path: /spec/destination/namespace
      value: ${{values.project_name | trim | dump}}
    - op: replace
      path: /spec/project
      value: ${{values.project_name | dump}}
    - op: replace
      path: /spec/source/repoURL
      value: https://github.com/${{ values.project_name }}/${{ values.application_name }}.git
# END ArgoCD
  {% endif %}
