apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "${{values.project_name }}_${{values.application_name }}"
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- else %}
  description: 
    project: ${{values.project_name | dump }}
    application: ${{values.application_name | dump }}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: ${{values.owner | dump}}
