---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- https://github.com/Tomelin/argocd-appProject/common

patches:
- target:
    kind: ${{values.project_name | dump}}
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: newproject
- target:
    kind: Application
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: teste123
