---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
{% if values.argocd %}
- https://github.com/Tomelin/argocd-appProject/common
{% else %}
patches:
{% if values.argocd %}
# STARTS ArgoCD
- target:
    kind: AppProject
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: ${{values.project_name | dump}}
    - op: replace
      path: /spec/destinations/0/namespace
      value: ${{values.namespace | dump}}
- target:
    kind: Application
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: ${{values.project_name | dump}}
    - op: replace
      path: /spec/destination/namespace
      value: ${{values.namespace | dump}}
    - op: replace
      path: /spec/project
      value: ${{values.project_name | dump}}
    - op: replace
      path: /spec/source/repoURL
      value: https://${{ (values.destination)["host"] }}/${{ (values.destination)["owner"] }}/${{ (values.destination)["repo"] }}.git
# END ArgoCD
{% else %}

# # enabledDB variable
# enabledDB ${{values.enabledDB }}
# database ${{values.enabledDB.database}}

# databaselower {{values.enabledDB.database|lower}}
# databaselower2 ${{values.enabledDB.database}}

# databaseKind ${{values.enabledDB.databaseKind }}
# databaseKind2 ${{values.enabledDB.database.databaseKind }}
# databaseVersion ${{values.enabledDB.databaseVersion }}
# databaseVersion2 ${{values.enabledDB.database.databaseVersion}}
# databaseVersion3 ${{values.enabledDB.databaseKind.databaseVersion}}


