---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
# repository of Argocd
- https://github.com/Tomelin/argocd-appProject/common

patches:
# Start patche to argocd
- path: ./argocd/appProject.yaml
- path: ./argocd/application.yaml
# End patche to argocd

# enabledDB variable
enabledDB ${{values.enabledDB }}
database ${{values.enabledDB.database}}

databaselower {{values.enabledDB.database|lower}}
databaselower2 ${{values.enabledDB.database|}}

databaseKind ${{values.enabledDB.databaseKind }}
databaseKind2 ${{values.enabledDB.database.databaseKind }}
databaseVersion ${{values.enabledDB.databaseVersion }}
databaseVersion2 ${{values.enabledDB.database.databaseVersion}}
databaseVersion3 ${{values.enabledDB.databaseKind.databaseVersion}}



# start enabledDB loop
{% for item in values.enabledDB %}
  Value: {{ item }}
{% endfor %} 
# end enabledDB loop

{% for i in "values" | list %}
item: {{ i }}
{% endfor %}

# echo "Hi my name is ${{ values.name }}, and you can fine me at ${{ values.url }}!"
# {% if values.enabledDB %}
# echo "You have enabled your database!"
# {% endif %}

{% for item in values.project_name %}
  Value: {{ item }}
{% endfor %}  

{% for item in values %}
  Value: {{ item }}
{% endfor %}  

  {% for idx in values %}
  Value: {{ idx }}
  index: {{ idx.index }}
{% endfor %}  

{% for row in values %}
value => {{ row }}
value => {{ row.index }}

  {# new row #}
  <tr>
  {% set rowloop = loop %}
  {% for cell in row %}
    <td>
        row (rowloop.index):{{ rowloop.index }}
        column (loop.index): {{ loop.index }}
        cell: {{ cell }}
    </td>
  {% endfor %}
  </tr>
{% endfor %}
