---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
# repository of Argocd
- https://github.com/Tomelin/argocd-appProject/common

patches:
# Start patche to argocd
- path: ./argocd/appProject.yaml
- path: ./argocd/application.yaml
# End patche to argocd

# enabledDB variable
enabledDB ${{values.enabledDB }}
database ${{values.enabledDB.database}}

databaselower {{values.enabledDB.database|lower}}
databaselower2 ${{values.enabledDB.database}}

databaseKind ${{values.enabledDB.databaseKind }}
databaseKind2 ${{values.enabledDB.database.databaseKind }}
databaseVersion ${{values.enabledDB.databaseVersion }}
databaseVersion2 ${{values.enabledDB.database.databaseVersion}}
databaseVersion3 ${{values.enabledDB.databaseKind.databaseVersion}}


