---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
 {%- if values.argocd %}
- https://github.com/Tomelin/argocd-appProject/common
 {% endif %}
 {%- if values.enabledDB.database %}
- https://github.com/Tomelin/crossplane/postgresql
 {% endif %}
 {%- if values.enabledDB.database %}
- https://github.com/Tomelin/backstage-templates/kuberntes
 {% endif %}


patches:
{%- if values.argocd %}
# STARTS ArgoCD
- target:
    kind: AppProject
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: ${{values.project_name | dump}}
    - op: replace
      path: /spec/destinations/0/namespace
      value: ${{values.project_name | dump}}
- target:
    kind: Application
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: ${{values.project_name | trim | dump}}
    - op: replace
      path: /spec/destination/namespace
      value: ${{values.project_name | trim | dump}}
    - op: replace
      path: /spec/project
      value: ${{values.project_name | dump}}
    - op: replace
      path: /spec/source/repoURL
      value: https://github.com/${{ values.project_name }}/${{ values.application_name }}.git
# END ArgoCD
  {% endif %}

{%- if values.enabledDB.database %}
# STARTS PostgreSQLServer
- target:
    kind: ResourceGroup
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: ${{values.project_name | dump}}
- target:
    kind: PostgreSQLServer
    name: .*
  patch: |-
    - op: replace
      path: /spec/forProvider/resourceGroupNameRef/name
      value: ${{values.project_name | trim | dump}}
    - op: replace
      path: /metadata/name
      value: ${{values.application_name | trim | dump}}
# END PostgreSQLServer
  {% endif %}

{%- if values.microservice %}
# STARTS Microservice
- target:
    kind: Deployment
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: ${{values.application_name | dump}}
    - op: add
      path: /metadata/namespace
      value: ${{values.project_name | dump}}
    - op: replace
      path: /metadata/labels/app
      value: ${{values.application_name | dump}}
- target:
    kind: Service
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: ${{values.application_name | dump}}
    - op: add
      path: /metadata/namespace
      value: ${{values.project_name | dump}}
    - op: replace
      path: /metadata/labels/app
      value: ${{values.application_name | dump}}
    - op: replace
      path: /spec/selector/apappp
      value: ${{values.application_name | dump}}  
- target:
    kind: HorizontalPodAutoscaler
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: ${{values.application_name | dump}}
    - op: add
      path: /metadata/namespace
      value: ${{values.project_name | dump}}
    - op: add
      path: /metadata/labels/app
      value: ${{values.application_name | dump}}
    - op: replace
      path: /spec/scaleTargetRef/name
      value: ${{values.application_name | dump}}      
# END Microservice
  {% endif %}
